[[redirects]]
  from = "/*"
  to = "/"
  status = 200

  [[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src  'self' 'self https://apis.google.com  *.fontawesome.com; img-src 'self  https://imagekit.io/ ''unsafe-inline'; https://*.googleapis/*/  https://*.fontawesome.com/*/ script-src 'self' 'unsafe-eval'; object-src 'self';"
    Content-Security-Policy = "default-src 'none'; style-src data: 'unsafe-inline'; img-src https://ik.imagekit.io/aneudyimages/*; font-src https://fontawesome.com"
    X-Content-Security-Policy = "default-src 'none'; style-src data: 'unsafe-inline'; img-src https://ik.imagekit.io/aneudyimages/*; font-src https://fontawesome.com"
    X-WebKit-CSP: "default-src 'none'; style-src data: 'unsafe-inline'; img-src https://ik.imagekit.io/aneudyimages/*; font-src https://fontawesome.com"