[[redirects]]
  from = "/*"
  to = "/"
  status = 200

  [[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src  'self' 'self https://apis.google.com 'unsafe-inline'; https://*.googleapis/*/  https://*.imagekit.io/*/ https://*.fontawesome.com/*/ script-src 'self' 'unsafe-eval'; object-src 'self';"